### ISSUE TITLE
Notice: Undefined index: complaintFeedbackType

### ISSUE THREAD

**Issue by Serhii-DV** [Teknasyon-Teknoloji/aws-ses-notification#4]
Started to get new notices:

```
Notice: Undefined index: complaintFeedbackType in /var/app/current/vendor/teknasyon-teknoloji/aws-ses-notification/src/Email/ComplaintEmail.php line 17

0 /var/app/current/vendor/teknasyon-teknoloji/aws-ses-notification/src/Email/ComplaintEmail.php(17): error_handler(8, 'Undefined index...', '/var/app/curren...', 17, Array)
#1 /var/app/current/vendor/teknasyon-teknoloji/aws-ses-notification/src/Email/BaseEmail.php(37): Teknasyon\AwsSesNotification\Email\ComplaintEmail->__construct(Array)
#2 /var/app/current/vendor/teknasyon-teknoloji/aws-ses-notification/src/Dispatcher.php(29): Teknasyon\AwsSesNotification\Email\BaseEmail::factory(Object(Aws\Sns\Message))
...
```

It seems like `complaintFeedbackType` not always has value.

**Comment by fustundag** [comment]
Thanks for report. I have fixed "Notice"
